CREATE TABLE IF NOT EXISTS Phonetics (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    word_id INTEGER NOT NULL,
    phonetic TEXT NOT NULL,
    FOREIGN KEY (word_id) REFERENCES Word(id) ON DELETE CASCADE
);